#ifndef MORIOR_GAMES_DEFINITIONS_H
#define MORIOR_GAMES_DEFINITIONS_H

#define IMAGE_SIZE 28
#define INPUT_NEURONS 784
#define HIDDEN_NEURONS 128
#define OUTPUT_NEURONS 10
#define LEARNING_RATE 0.3

#endif
